# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LED_FORM',
            fields=[
                ('switch', models.CharField(max_length=30)),
                ('id', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
