# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170501_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led_form',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
